# Generated by Django 4.2.7 on 2023-11-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
    ]
