# Generated by Django 4.2.7 on 2023-11-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_opponent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tounament',
            new_name='Tournament',
        ),
    ]
