# Generated by Django 4.2.7 on 2023-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
