# Generated by Django 4.2.7 on 2023-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tournament_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='opponent',
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='stage_modified',
            field=models.BooleanField(default=False),
        ),
    ]
