# Generated by Django 4.2.7 on 2023-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_opponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='score',
            new_name='opponent_score',
        ),
        migrations.AddField(
            model_name='team',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
