# Generated by Django 4.2.7 on 2024-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_score_team_opponent_score_team_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
