# Generated by Django 4.2.7 on 2024-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarters',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarters',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
