# Generated by Django 4.2.7 on 2024-01-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quarters_opponent_score_quarters_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarters',
            name='home_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quarters',
            name='opponent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
