# Generated by Django 4.2.7 on 2024-01-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quarters_home_team_quarters_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarters',
            name='score_modified',
            field=models.BooleanField(default=False),
        ),
    ]
