# Generated by Django 4.2.7 on 2024-01-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quarters_score_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarters',
            name='home_team',
        ),
    ]
